version: '3.8'

services:
  postgres:
    image: postgres:13
    env_file:
      - .env
    ports:
      - "5432:5432"
    networks:
      - app-network

  redis:
    image: redis:6.2
    ports:
      - "6379:6379"
    networks:
      - app-network

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    networks:
      - kafka-network

  kafka:
    container_name: kafka
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper
    networks:
      - kafka-network

  consumer-service:
    image: consumer
    ports:
      - "8081:8081"
    environment:
      SPRING_KAFKA_BOOTSTRAP-SERVERS: "kafka:9092"
    networks:
      - kafka-network

  app:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
      - kafka
    networks:
      - app-network
      - kafka-network

networks:
  app-network:
    driver: bridge
  kafka-network:
    driver: bridge